### ISSUE TITLE
Yoh

### ISSUE THREAD

**Issue by Leejit** [Awzaw/RankPoints#1]
on two different websites, you have two different shown examples for how to input the rank/point data....

Which is it ? 

Ranks: Guest Mod God Points: 0 30 60

or 

Ranks: Guest Mod God
Points: 0 30 60

or

Ranks:
Guest
Mod
God
Points:
0
30
60

HOW DOES IT WORK... SHOW AN ACTUAL EXAMPLE.

**Comment by Awzaw** [comment]
Sorry about that, poggit had formatting issues and my read.me and config were outdated :-/ fixed now: https://poggit.pmmp.io/p/RankPoints/

**Comment by Leejit** [comment]
Thanks..... bout time ;P 

xD
